[package]
name = "web_server_by_zihao"
version = "0.1.1"
edition = "2021"
authors = ["2638779206@qq.com"]
description = "exercise by The Book"
license = "MIT OR Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
